version: "3.3"

services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    hostname: frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true